<?php

/**
 * @Author: Codehaveli
 * @Date:   2020-11-22 21:23:31
 * @Last Modified by:   Codehaveli
 * @Website: www.codehaveli.com
 * @Email: hello@codehaveli.com
 * @Last Modified time: 2020-11-22 23:15:53
 */


?>

<h3 style="text-align: center; margin-top: 10px;">Generated by <a target="_blank" href="https://wordpress.org/plugins/codehaveli-bitly-url-shortener/">Codehaveli Bitly URL Shortener</a></h3>